### ISSUE TITLE
table/user_cart_item

### ISSUE THREAD

**Issue by wijeremy** [wijeremy/e-commerce-admin-gui#13]

**Comment by javivilchis** [comment]
There is still an error in this model: 

here is the error log: 
`Executing (default): CREATE TABLE IF NOT EXISTS `cart_item` (`id` INTEGER NOT NULL auto_increment , `session_id` VARCHAR(255) NOT NULL, `product_id` VARCHAR(255) NOT NULL, `quantity` INTEGER NOT NULL, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`session_id`) REFERENCES `user_shopping_session` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`product_id`) REFERENCES `product` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
(node:28865) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: Referencing column 'session_id' and referenced column 'id' in foreign key constraint 'cart_item_ibfk_1' are incompatible.
    at Query.formatError (/Users/jvilchis/SMU/e-commerce-admin-gui/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)
    at Query.run (/Users/jvilchis/SMU/e-commerce-admin-gui/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/jvilchis/SMU/e-commerce-admin-gui/node_modules/sequelize/lib/sequelize.js:619:16
    at async MySQLQueryInterface.createTable (/Users/jvilchis/SMU/e-commerce-admin-gui/node_modules/sequelize/lib/dialects/abstract/query-interface.js:225:12)
    at async Function.sync (/Users/jvilchis/SMU/e-commerce-admin-gui/node_modules/sequelize/lib/model.js:1300:5)
    at async Sequelize.sync (/Users/jvilchis/SMU/e-commerce-admin-gui/node_modules/sequelize/lib/sequelize.js:793:35)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28865) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28865) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
